### PR TITLE
Delegation with extra arguments at arbitrary positions

### PR DESCRIPTION
**Pull request by kondziu**
Stemming from the conversation in PR #31:

The idea is to add argument expressions at arbitrary positions into the delegated methods. These expressions are marked by square brackets. The method would generate a signature without these arguments, but the call to the method on the inner object would generate these expressions in the argument list at the appropriate positions.

Example:

```rust
delegate! {
    to self.inner {
        pub fn method(&self, a: u32, [ 0 ], c: u32, [ self.default_offset ]) -> u32;
    }
}
```

Generates into:

```rust
pub fn method(&self, a: u32, c: u32) -> u32 {
    self.inner.method(a, 0, c, self.default_offset)
}
```

### CODE REVIEW

**Comment by kondziu** [comment]
Basically works. Things to do: documentation, testing, refactoring.

**Comment by Kobzol** [comment]
I see you're making steady progress! Please rebase onto master and mark the PR as ready for review if you think it's ready for review :)

**Comment by kondziu** [comment]
Not yet ready for review ;) 

Things to do: nip and tuck on code for cleanliness and aesthetics.

**Comment by kondziu** [comment]
I made a mess with my branches, and in the process the PR got closed accidentally. Since nothing was really lost here, I'll recreate it with a squashed branch. Sorry for the inconvenience.

**Pull request closed without merging**
